# Generated by Django 4.2.6 on 2023-10-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccuntApp', '0002_alter_guest_birth_date_alter_guest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='birth_date',
        ),
    ]
