# Generated by Django 4.2.6 on 2023-10-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccuntApp', '0003_remove_guest_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
