# Generated by Django 4.2.6 on 2023-10-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_room_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='benefit',
        ),
        migrations.AddField(
            model_name='book',
            name='benefit',
            field=models.CharField(blank=True, choices=[('ser', 'Room Service'), ('brf', 'Breakfast'), ('lun', 'Lunch'), ('ent', 'Entertainment')], max_length=3, null=True),
        ),
    ]
