# Generated by Django 4.2.6 on 2023-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_remove_room_benefit_book_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='benefit',
            field=models.CharField(blank=True, choices=[('Room Service', 'Room Service'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Entertainment', 'Entertainment')], max_length=20, null=True),
        ),
    ]
